version: '3'

networks:
  wordpress-network:
      driver: bridge

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "0.0.0.0:5006:3306"
    networks: 
      - wordpress-network
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  apache:
    image: webdevops/apache:latest
    environment:
      - ALLOW_OVERRIDE=true
    volumes:
      - ./src:/app
    ports:
      - "0.0.0.0:5000:80"
    links:
      - db:mysql
    depends_on:
      - db
    networks:
      - wordpress-network
