version: '3'

networks:
  wordpress-network:
      driver: bridge

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: admin
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: intranet
    ports:
      - "127.0.0.1:5001:3306"
    networks: 
      - wordpress-network
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  wordpress:
    depends_on:
      - db
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: "root"
    ports:
     - "127.0.0.1:5000:80"
    networks:
      - wordpress-network
    volumes:
      - ./:/var/www/html/