version: '3'

networks:
  wordpress-network:
      driver: bridge

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: admin
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: intranet
    ports:
      - "127.0.0.1:5001:3306"
    networks: 
      - wordpress-network
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  apache:
    image: webdevops/apache:latest
    command: bash -c "apt update && apt -y upgrade && apt install -y libapache2-mod-php php-mysql php-pear php-fpm php-dev php-zip php-curl php-xmlrpc php-gd php-mbstring php-xml"
    environment:
      - ALLOW_OVERRIDE=true
    volumes:
      - ./src:/app
    ports:
      - "127.0.0.1:5000:80"
    depends_on:
      - db